-- DDL

CREATE DATABASE Ex1_1;

USE Ex1_1;

CREATE TABLE Company
(
	CompanyId INT PRIMARY KEY IDENTITY,
	CompanyName VARCHAR(50) NOT NULL
);

CREATE TABLE Client
(
	ClientId INT PRIMARY KEY IDENTITY,
	ClientName VARCHAR(50) NOT NULL,
	ClientCPF CHAR(11) NOT NULL
);

CREATE TABLE Model
(
	ModelId  INT PRIMARY KEY IDENTITY,
	ModelName VARCHAR(30) NOT NULL,
);

CREATE TABLE Brand
(
	BrandId INT PRIMARY KEY IDENTITY,
	BrandName VARCHAR(50) NOT NULL,
);

CREATE TABLE Vehicle
(
	VehicleId INT PRIMARY KEY IDENTITY,
	CompanyId INT FOREIGN KEY REFERENCES Company(CompanyId),
	BrandId INT FOREIGN KEY REFERENCES Brand(BrandId),
	ModelId INT FOREIGN KEY REFERENCES Model(ModelId),
	LicensePlate CHAR(7) NOT NULL
);

CREATE TABLE Rent
(
	RentId INT PRIMARY KEY IDENTITY,
	ClientId INT FOREIGN KEY REFERENCES Client(ClientId),
	VehicleId INT FOREIGN KEY REFERENCES Vehicle(VehicleId),
	WithdrawalDate DATE NOT NULL,
	ReturnDate DATE NOT NULL
);
